# Generated by Django 4.2.9 on 2024-01-15 03:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20)),
                ('statement', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('dp', models.FileField(blank=True, null=True, upload_to='')),
                ('email', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PostTable',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=350)),
                ('content', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usertable')),
            ],
        ),
    ]
